name: PYTHON APPLICATION
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install matplotlib
      run: pip install matplotlib

    - name: Run the assignment
      run: python ASSIGNMENT_1.py

    - name: Upload plots as artifacts
      uses: actions/upload-artifact@v4
      with:
        name: sorting-plots
        path: |
          t_n_vs_n.png
          time_vs_n.png
